## NUMPY
- stands for numerical python
- used for data manipulation (means somthing we have to do on data).
- it basically focuses on row,
    - 1 row = 1D Numpy array
    - 2 rows = 2D Numpy array

### **1. Array**
- An array in Python is a way to store multiple values in a single variable. 
- Python doesn’t have a built-in array data type like some other languages thats why to use we need to import array module.
- By deafult apply for loop - for each value in array
- If the original array contains a string, all other elements are automatically converted to strings after printing. **str > float > int > bool**
- Nested array is not possible as every item in array should be either fundamental or advance datatype not mix of them.
- If a list items printed without comma then it is array.

#### **1.1 Ways to use array**

#### **1.1.1 By array module**

- syntax 
    <pre>
    import array as arr
    array_name = arr . array_function('datatype' , [list of item])
    print(array_name)
    <pre>

- only support basic types 
    - 'i' : signed integer
    - 'f' : float
    - 'd' : double

In [ ]:
# array module

import array as arr
a=arr.array('f',[1,2,3,4])
print(a)

array('f', [1.0, 2.0, 3.0, 4.0])


#### **1.1.2 By numpy array**
- syntax

    <pre>
    import numpy as np
    array_name = np . array_function([list of items])
    print(array_name)
    <pre>

- Creation
    1. array()
    2. arange()
    3. zeros()
    4. ones()
    5. random.randint()
    6. tolist()

- Extraction
    - accessing single value - indexing
    - accessing multiple values if they have pattern - slicing 
    - accessing multiple values if they have no pattern - indexing - array[[list of index number]]
    - accessing single or multiple values based on condition - array[condition]

- Modification
    1. Adding
        - Single value --> np.append(array_name , value)
        - Multiple values --> np.append(array_name , [list of items])

    2. Replace
        - Single value --> array_name[index]
        - Multiple index with single value --> array_name[[list of index no.]]
        - Multiple index with multiple values --> array_name[[list of index no.]] = [list of number] 

    3. Deletion
        - Single value --> np.delete(array_name , index no)
        - Multiple values --> np.delete(array_name , [multiple index no.])


#### **1.1.2.1 Creation**

In [27]:
import numpy as np

In [28]:
# 1.array()

a=np.array([1,2,3])
print(a)

[1 2 3]


In [29]:
# 2.arange()

arr=np.arange(1,5,3)
print(arr)

[1 4]


In [30]:
# 3.Zeros(1arg) - generate array of zeros and by deafult give float output

arr=np.zeros(4,) 
print(arr)

[0. 0. 0. 0.]


In [31]:
# 4.Ones(1arg) - generate array of ones and by deafult give float output

arr=np.ones(4,)
print(arr)

[1. 1. 1. 1.]


In [32]:
# 5.random.randint() - return random integer from start(inclusive), end(exclusive), no of samples

arr=np.random.randint(5,10,3)
print(arr)

[8 6 8]


In [33]:
# 6.tolist()

#### **1.1.2.2 Extraction**

In [35]:
import numpy as np
arr=np.array([10,21,34,85,54,91])

In [37]:
# single value
print(arr[0])
print(arr[5])

10
91


In [ ]:
# multiple values - slicing
print(arr[0:3])
print(arr[1:5:2])

[10 21 34]
[21 85]


In [40]:
# multiple values - indexing
print(arr[[1,3,5]])

[21 85 91]


In [11]:
# multiple values - condtion based
print(arr>40)
print(arr[arr>40])

[False False False  True  True False]
[85 54]


#### **1.1.2.3 Modification**

In [16]:
import numpy as np
arr=np.array([10,1,34,85,54,9])

In [ ]:
# adding single value ---> np.append(array_name , value)
np.append(arr,100)

array([ 10,  21,  34,  85,  54,  91, 100])

In [ ]:
# adding multiple items ---> np.append(array_name , [list of values])
np.append(arr,[20,40])

array([10, 21, 34, 85, 54, 91, 20, 40])

In [ ]:
# replace single item ---> array_name[index no.] = value
arr[2]=30
print(arr)

[10 21 30 85 54 91]


In [18]:
# replace multiple index with single no. ---> array_name[[list of index no]] = value
arr[[2,3]]=11
print(arr)

# or

a = [2,3]
arr[a] = 11
print(arr)

[10  1 11 11 54  9]
[10  1 11 11 54  9]


In [ ]:
# replace multiple index with multiple no. ---> array_name[[list of index no.]] = [list of values]
arr[[0,1]]=[10,20]
print(arr)

[10 20 11 11 54  9]


#### **1.1.2.4 Deletion**

In [ ]:
# single value - np.delete( array_name , index no)
np.delete(arr,2)

array([10, 21, 85, 54, 91])

In [ ]:
# multiple value - np.delete(array_name , [list of index no.])
np.delete(arr,[0,1])

array([30, 85, 54, 91])

#### **1.1.2.5 Sorting and Copy**

In [ ]:
# sorting
arr=np.array([38,12,56,37,50])
arr.sort()
print(arr)

[12 37 38 50 56]


In [ ]:
# deep copy
a= arr
b=a
print(a)
print(b)

[12 37 38 50 56]
[12 37 38 50 56]


In [37]:
# shallow copy
a=arr
b=a.copy()
b=np.append(b,100)
print(a)
print(b)

[12 37 38 50 56]
[ 12  37  38  50  56 100]


#### **1.1.2.6 Operations/ Applications**
- It will check the shape of the array if it is same then only operation is possible otherwise not.
- Every value of one array is compare to each value of other in order to operate.

1. Arithmatic Operation
2. Comparision Operation 
3. Mathematical operation 

In [ ]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
a3=np.array([10,20])
a4=np.array([5,6,7,8])

##### **1.1.2.6.1 Arithmatic Operation**

In [42]:
x= a1+10 # operation apply for each value of a1
print(x)

[11 12 13 14]


In [44]:
z=a1*a2
print(z)

[ 5 12 21 32]


In [ ]:
# y=a1+a3   # not possible as both array have different shapes

##### **1.1.2.6.2 Comparision Operator**

In [49]:
a1==a2

array([False, False, False, False])

In [53]:
a4>=a1

array([ True,  True,  True,  True])

In [55]:
# a3==a1 # not possible coz differnt shape

In [57]:
# np.array_equal() ---> check overal all c=value of two array and return bool value.

np.array_equal(a1,a2)

False

In [58]:
np.array_equal(a2,a4)

True

##### **1.1.2.6.3 Mathematical Operation**

In [ ]:
# np.exp(array_name) ---> return e**array_name for each value
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [60]:
# np.log(array_name) ---> return log(array_name) for each value 
np.log(a3)

array([2.30258509, 2.99573227])