## NUMPY
- stands for numerical python
- used for data manipulation (means somthing we have to do on data).
- it basically focuses on row,
    - 1 row = 1D Numpy array
    - 2 rows = 2D Numpy array

### **1. Array**
- An array in Python is a way to store multiple values in a single variable. 
- Python doesn’t have a built-in array data type like some other languages thats why to use we need to import array module.
- By deafult apply for loop - for each value in array
- If the original array contains a string, all other elements are automatically converted to strings after printing. **str > float > int > bool**
- Nested array is not possible as every item in array should be either fundamental or advance datatype not mix of them.
- If a list items printed without comma then it is array.

#### **1.1 Ways to use array**

#### **1.1.1 By array module**

- syntax 
    <pre>
    import array as arr
    array_name = arr . array_function('datatype' , [list of item])
    print(array_name)
    <pre>

- only support basic types 
    - 'i' : signed integer
    - 'f' : float
    - 'd' : double

In [ ]:
# array module

import array as arr
a=arr.array('f',[1,2,3,4])
print(a)

array('f', [1.0, 2.0, 3.0, 4.0])


#### **1.1.2 By numpy array**
- syntax

    <pre>
    import numpy as np
    array_name = np . array_function([list of items])
    print(array_name)
    <pre>

- Creation
    1. array()
    2. arange()
    3. zeros()
    4. ones()
    5. random.randint()
    6. tolist()

- Extraction
    - accessing single value - indexing
    - accessing multiple values if they have pattern - slicing 
    - accessing multiple values if they have no pattern - indexing - array[[list of index number]]
    - accessing single or multiple values based on condition - array[condition]

- Modification
    1. Adding
        - Single value --> np.append(array_name , value)
        - Multiple values --> np.append(array_name , [list of items])

    2. Replace
        - Single value --> array_name[index]
        - Multiple index with single value --> array_name[[list of index no.]]
        - Multiple index with multiple values --> array_name[[list of index no.]] = [list of number] 

    3. Deletion
        - Single value --> np.delete(array_name , index no)
        - Multiple values --> np.delete(array_name , [multiple index no.])


#### 1.1.2.1 Creation

In [27]:
import numpy as np

In [28]:
# 1.array()

a=np.array([1,2,3])
print(a)

[1 2 3]


In [29]:
# 2.arange()

arr=np.arange(1,5,3)
print(arr)

[1 4]


In [30]:
# 3.Zeros(1arg) - generate array of zeros and by deafult give float output

arr=np.zeros(4,) 
print(arr)

[0. 0. 0. 0.]


In [31]:
# 4.Ones(1arg) - generate array of ones and by deafult give float output

arr=np.ones(4,)
print(arr)

[1. 1. 1. 1.]


In [32]:
# 5.random.randint() - return random integer from start(inclusive), end(exclusive), no of samples

arr=np.random.randint(5,10,3)
print(arr)

[8 6 8]


In [33]:
# 6.tolist()

#### 1.1.2.2 Extraction

In [35]:
import numpy as np
arr=np.array([10,21,34,85,54,91])

In [37]:
# single value
print(arr[0])
print(arr[5])

10
91


In [ ]:
# multiple values - slicing
print(arr[0:3])
print(arr[1:5:2])

[10 21 34]
[21 85]


In [40]:
# multiple values - indexing
print(arr[[1,3,5]])

[21 85 91]


In [41]:
# multiple values - condtion based
print(arr[arr>40])

[85 54 91]


#### 1.1.2.3 Modification

In [ ]:
import numpy as np
arr=np.array([10,1,34,85,54,9])

In [45]:
# adding single value
np.append(arr,100)

array([ 10,  21,  34,  85,  54,  91, 100])

In [46]:
# adding multiple items
np.append(arr,[20,40])

array([10, 21, 34, 85, 54, 91, 20, 40])

In [48]:
# replace single item
arr[2]=30
print(arr)

[10 21 30 85 54 91]


In [50]:
# replace multiple index with single no.
arr[2,3]=11
print(arr)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [58]:
# replace multiple index with multiple no.
arr[0,1]=[10,20]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

#### 1.1.2.4 Deletion

In [ ]:
# dingle value
np.delete(arr,2)

array([10, 21, 85, 54, 91])

In [59]:
# multiple value
np.delete(arr,[0,1])

array([30, 85, 54, 91])