## 2D NUMPY ARRAY
- 2 rows = 2D array
- comibantion of multiple 1D array called 2D array
- combination od multiple 2D are called 3D but they lie under 2D category.
- when creating  2D array the length of the list must be of same size.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
print(a.ndim)   # number of dimensions
print(a.shape)  # tuple representing the size of the array (rows, columns)
# The number of items in the tuple a.shape is equal to a.ndim.

2
(2, 3)


### **1.1 Creation**
1. zeros
2. ones
3. identity matrix
4. diagonal matrix

In [ ]:
#Zeroes
import numpy as np
a=np.zeros((2,3), dtype=int) # dtype is optional
print(a)

[[0 0 0]
 [0 0 0]]


In [ ]:
# ones
import numpy as np
a=np.ones((2,2)) # dtype is optional
print(a)

[[1. 1.]
 [1. 1.]]


### **1.2 Extraction**